### ISSUE TITLE
Question: How to get or change underlying libarchive version that is in use?

### ISSUE THREAD

**Issue by Envek** [AMekss/archive_io#1]
Hi! Thank you for a nice gem.

I'm trying to play with it on OS X machine with some huge RAR archives (3 GiBs with files of 2 and 18 GBcompressed XML in it).

[Libarchive wiki says](https://github.com/libarchive/libarchive/wiki/LibarchiveFormats), that RAR format is supported since 3.0, so I've installed latest libarchive (3.2.1) from Homebrew.

But I'm trying next snippet:

``` ruby
require 'archive_io'
archive = ArchiveIO.open(File.expand_path('~/Downloads/fias_xml.rar'))
archive.each { |cursor| puts cursor.pathname }
```

and getting such an error:

```
ArchiveIO::LibArchive::Error: Unrecognized archive format
```
# Questions
1. How I can get know which libarchive (system or from Homebrew) is being used?
2. How I can tell Ruby FFI to use libarchive from Homebrew?

I've played with Ruby's `$LOAD_PATH` and system `LD_LIBRARY_PATH` environment variable, but with no luck (tried to feed `/usr/local/opt/libarchive/lib` to them).

Any thoughts?

You can download archive for testing from this page: http://fias.nalog.ru/Updates.aspx (e.g. http://fias.nalog.ru/Public/Downloads/20160825/fias_delta_xml.rar )

**Comment by AMekss** [comment]
I had the same problem with 7zip on MacOS Yosemite (which comes with libarchive 2.8.x by default). That's how I did the upgrade to libarchive 3.2.1:

```
brew install libarchive
brew link libarchive --force
```

Here is how you can check the version used by your system:

```
tar --version
```

And you can execute this in `./bin/console` to check what version is being used by the gem (should be the same version as from the `tar --version`)

``` ruby
ArchiveIO::LibArchive::archive_version_string
```

Hope this will help.

**Comment by Envek** [comment]
Actually I want to avoid force-linking of Homebrew `libarchive` somehow.

But anyway now it works.

Thank you for `ArchiveIO::LibArchive::archive_version_string`!

I've experimented with various environment variables and got curious results:

```
$ DYLD_LIBRARY_PATH=/usr/local/Cellar/libarchive/3.2.1/lib ruby -r 'archive_io' -e 'puts ArchiveIO::LibArchive::archive_version_string'
libarchive 2.8.3
$ DYLD_LIBRARY_PATH=/usr/local/Cellar/libarchive/3.2.1/lib `rbenv which ruby` -r 'archive_io' -e 'puts ArchiveIO::LibArchive::archive_version_string'
libarchive 3.2.1
```

But this sounds like a beginning of another issue in another repo :-)

Answers to my questions summarized:
1. > How I can get know which libarchive (system or from Homebrew) is being used?
   
   ``` ruby
   ArchiveIO::LibArchive::archive_version_string
   ```
2. > How I can tell Ruby FFI to use libarchive from Homebrew?
   
   Specify path to directory containing libarchive dynamic library in `DYLD_LIBRARY_PATH` environment variable when executing ruby interpreter directly.
